### ISSUE TITLE
Idle Alert plays even with it disabled

### ISSUE THREAD

**Issue by Snoogens101** [Skykeiron/SoundAlerts#1]
I've just got the Health alert enabled, however it still plays the Idle alert when you're idling.

**Comment by Skykeiron** [comment]
> I've just got the Health alert enabled, however it still plays the Idle alert when you're idling.

Hey, thanks for the report I've been meaning to fix this I'll push an update today fixing this

**Comment by Skykeiron** [comment]
I've pushed a fix for this, whenever plugins get updated this should be live.
